---
stages:
- name: Build
  inputs:
  - url: https://github.com/IBM-Cloud/cfee-service-broker-kubernetes.git
    type: git
    branch: master
    dir_name: null
  triggers:
  - type: commit
  permission:
    execute: TOOLCHAIN_ADMINS
  properties:
  - name: PIPELINE_KUBERNETES_CLUSTER_NAME
    value: cfee-tutorial-cluster
    type: text
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: cr
    script: |-
      #!/bin/bash
      ./scripts/pipeline-BUILD.sh
    namespace: cfee-tutorial
    image_name: broker-impl
    target:
      region_id: ibm:yp:us-east
      api_key: 19fnpqGnM+Ys1IQSRJ5/JZvYhpyQwncqklnajJJNZ8kGK/yBIcaj+UKNOFp2/SjcQivgI3QCx+70jKTkn0K4zQ==
      account_guid: e97a8c01ac694e308ef3ad77958e7d50
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  permission:
    execute: TOOLCHAIN_ADMINS
  properties:
  - name: buildprops
    value: build.properties
    type: file
  - name: API_KEY
    type: secure
  jobs:
  - name: Deploy Service Broker
    type: deployer
    deploy_type: kubernetes
    target:
      region_id: ibm:yp:us-east
      api_key: 19fnpqGnM+Ys1IQSRJ5/JZvYhpyQwncqklnajJJNZ8kGK/yBIcaj+UKNOFp2/SjcQivgI3QCx+70jKTkn0K4zQ==
      account_guid: e97a8c01ac694e308ef3ad77958e7d50
      resource_group: default
      kubernetes_cluster: cfee-tutorial-cluster
    script: |-
      #!/bin/bash
      ./scripts/pipeline-DEPLOY-broker.sh
  - name: Deploy Services
    type: deployer
    deploy_type: cf
    target:
      region_id: ibm:yp:us-south
      organization: cps-van_staub@us.ibm.com
      space: cfee-tutorial
      api_key: cAnYuTk4dumV25gghck2rzEuwZVR31uzRrhmZbLlO/NbcpoNhvD3Dyj/jKPXOuYtQivgI3QCx+70jKTkn0K4zQ==
    script: |-
      #!/bin/bash
      ./scripts/pipeline-DEPLOY-services.sh
  - name: Deploy Welcome Service
    type: deployer
    deploy_type: cf
    target:
      region_id: ibm:yp:us-south
      organization: cfee-e97a8c01ac694e308ef3ad77958e7d50
      space: lw-cfee-demo
      application: welcome
      api_key: uWkIeNlGIqWyHyrC3vJ4I/pApWFDL7hkXhEnfoFTzWOuJWLeDMJa633puNbkjYj+QivgI3QCx+70jKTkn0K4zQ==
      cfee_env: cfee-tutorial
      cfee_host: https://api.cfee-tutorial-cluster.us-east.containers.appdomain.cloud
    script: |-
      #!/bin/bash
      ./scripts/pipeline-DEPLOY-welcome-app.sh
  - name: Deploy GetStartedNode
    type: deployer
    deploy_type: cf
    target:
      region_id: ibm:yp:us-south
      organization: cfee-e97a8c01ac694e308ef3ad77958e7d50
      space: lw-cfee-demo
      application: GetStartedNode
      api_key: uWkIeNlGIqWyHyrC3vJ4I/pApWFDL7hkXhEnfoFTzWOuJWLeDMJa633puNbkjYj+QivgI3QCx+70jKTkn0K4zQ==
      cfee_env: cfee-tutorial
      cfee_host: https://api.cfee-tutorial-cluster.us-east.containers.appdomain.cloud
    script: |-
      #!/bin/bash
      ./scripts/pipeline-DEPLOY-getstartednode.sh
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: http://lms-api/v1/messaging/webhook/publish
