---
stages:
- name: Build
  inputs:
  - type: git
    branch: ${GIT_BRANCH}
    service: ${GIT_REPO}
  triggers:
  - type: commit
  properties:
  - name: TARGET_CLUSTER_NAME
    value: ${TARGET_CLUSTER_NAME}
    type: text
  jobs:
  - name: Build
    type: builder
    build_type: cr
    namespace: ${REGISTRY_NAMESPACE}
    #image_name: ${IMAGE_NAME}
    image_name: broker-impl
    target:
      region_id: ${REGISTRY_REGION_ID}
      api_key: ${API_KEY}
    script: |
      #!/bin/bash
      ./scripts/pipeline-BUILD.sh
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: buildprops
    value: build.properties
    type: file
  - name: API_KEY
    type: secure
    value: ${API_KEY}
  jobs:
  - name: Deploy Service Broker
    type: deployer
    deploy_type: kubernetes
    target:
      region_id: ${TARGET_REGION_ID}
      api_key: ${API_KEY}
      resource_group: ${TARGET_RESOURCE_GROUP}
      kubernetes_cluster: ${TARGET_CLUSTER_NAME}
    script: |-
      #!/bin/bash
      ./scripts/pipeline-DEPLOY-broker.sh
  - name: Welcome App
    type: deployer
    deploy_type: cf
    target:
      organization: ${CFEE_ORG}
      space: ${CFEE_SPACE}
      application: welcome
      api_key: ${API_KEY}
      cfee_env: ${CFEE_ENV}
      cfee_host: ${CFEE_HOST}
    script: |-
      #!/bin/bash
      ./scripts/pipeline-DEPLOY-welcome-app.sh
  - name: Cloudant
    type: deployer
    deploy_type: kubernetes
    target:
      region_id: ${TARGET_REGION_ID}
      api_key: ${API_KEY}
      resource_group: ${TARGET_RESOURCE_GROUP}
      kubernetes_cluster: ${TARGET_CLUSTER_NAME}
    script: |-
      #!/bin/bash
      ./scripts/pipeline-DEPLOY-services.sh
  - name: GetStartedNode App
    type: deployer
    deploy_type: cf
    target:
      region_id: ${TARGET_REGION_ID}
      api_key: ${API_KEY}     
      organization: ${CFEE_ORG}
      space: ${CFEE_SPACE}
      application: GetStartedNode
      cfee_env: ${CFEE_ENV}
      cfee_host: ${CFEE_HOST}
    script: |-
      #!/bin/bash
      ./scripts/pipeline-DEPLOY-getstartednode.sh