---
stages:
- name: BUILD 
  inputs:
  - type: git
    branch: ${GIT_BRANCH}
    service: ${GIT_REPO}
  triggers:
  - type: commit
  properties:
  - name: TARGET_CLUSTER_NAME
    value: ${TARGET_CLUSTER_NAME}
  jobs:
  - name: Build
    type: builder
    build_type: cr
    #Target needs to be uodated.
    target:
      region_id: ${REGISTRY_REGION_ID}
      api_key: ${API_KEY}
    namespace: ${REGISTRY_NAMESPACE}
    image_name: <not applicable>    
    script: |-
      #!/bin/bash
      ./scripts/pipeline-BUILD.sh      
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build Docker images
  triggers:
  - type: stage
  properties:
  - name: buildprops
    value: build.properties
    type: file
  - name: TARGET_NAMESPACE
    value: ${TARGET_NAMESPACE}
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${TARGET_REGION_ID}
      api_key: ${API_KEY}
      kubernetes_cluster: ${TARGET_CLUSTER_NAME}
    script: |
      #!/bin/bash
      #./.bluemix/pipeline-DEPLOY.sh