---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: ${GIT_BRANCH}
    service: ${GIT_REPO}
  triggers:
  - type: commit
  properties:
  - name: TARGET_CLUSTER_NAME
    value: cfee-tutorial
    type: text
  jobs:
  - name: Build Docker image
    type: builder
    build_type: cr
    # artifact_dir: output
    namespace: ${REGISTRY_NAMESPACE}
    image_name: ${IMAGE_NAME}
    target:
      region_id: ${REGISTRY_REGION_ID}
      api_key: ${API_KEY}
    script: |
      #!/bin/bash
      ./scripts/pipeline-BUILD.sh
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: buildprops
    value: build.properties
    type: file
  - name: API_KEY
    type: secure
  jobs:
  - name: Deploy Service Broker
    type: deployer
    deploy_type: kubernetes
    target:
      region_id: ${REGISTRY_REGION_ID}
      api_key: ${API_KEY}
      resource_group: ${TARGET_RESOURCE_GROUP}
      kubernetes_cluster: ${TARGET_CLUSTER_NAME}
    script: |-
      #!/bin/bash
      ./scripts/pipeline-DEPLOY-broker.sh
  - name: Deploy Services
    type: deployer
    deploy_type: cf
    target:
      region_id: ${REGISTRY_REGION_ID}
      api_key: ${API_KEY}
      organization: ${todo cps-van_staub@us.ibm.com}
      space: {todo cfee-tutorial}
      api_key: {Todo ...}
      script: |-
      #!/bin/bash
      ./scripts/pipeline-DEPLOY-services.sh
  - name: Deploy Welcome Service
    type: deployer
    deploy_type: cf
    target:
      region_id: ${REGISTRY_REGION_ID}
      organization: {todo cfee-e97a8c01ac694e308ef3ad77958e7d50}
      space: {cf space todo lw-cfee-demo}
      application: welcome
      api_key: {Todo ...}
      cfee_env: {Todo cfee-tutorial}
      cfee_host: {Todo https://api.cfee-tutorial-cluster.us-east.containers.appdomain.cloud}
    script: |-
      #!/bin/bash
      ./scripts/pipeline-DEPLOY-welcome-app.sh
  - name: Deploy GetStartedNode
    type: deployer
    deploy_type: cf
    target:
      region_id: ${REGISTRY_REGION_ID}
      organization: {todo cfee-e97a8c01ac694e308ef3ad77958e7d50}
      space: {cf space todo lw-cfee-demo}
      application: GetStartedNode
      api_key: {Todo ...}
      cfee_env: {Todo cfee-tutorial}
      cfee_host: {Todo https://api.cfee-tutorial-cluster.us-east.containers.appdomain.cloud}
    script: |-
      #!/bin/bash
      ./scripts/pipeline-DEPLOY-getstartednode.sh